/*
 * hdr.h, 2007.02.26, SJ
 */

static char *mail_headers[] = {
   "From: ",
   "Subject: ",
   "To: ",
   "Reply-To: ",
   "Message-Id: ",
   "Return-Path: ",
   "X-Original-To: ",
   "Received: ",
   "Content-Type: ",
   "Content-Disposition: ",
   "Content-Transfer-Encoding: ",
   "Content-Description: ",
   "MIME-Version: ",
   "Date: ",
   "Resent-Date: ",
   "X-Clapf-spamicity: ",
   "Return-Path: ",
   "X-Original-To: ",
   "X-Autogenerated: ",
   "X-SpamTest-",
   "X-Mailer: ",
   "X-MimeOLE: ",
   "X-Priority: ",
   "X-MSMail-Priority: ",
   "User-Agent: ",
   "Status: ",
   "In-Reply-To: "
};

