/*
 * shdr.h, 2008.07.16, SJ
 */

/*static char *skip_headers[] = {
   "Date:",
   "Resent-Date:",
   "X-Clapf-spamicity:",
   "Return-Path:",
   "X-Original-To:",
   "X-Autogenerated:",
   "X-SpamTest-",
   "X-Mailer:",
   "X-MimeOLE:",
   "User-Agent:",
   "Status:",
   "X-Status:",
   "X-Keywords:",
   "In-Reply-To:",
   "MIME-Version:",
};*/

static char *weekdays[] = { "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" };
static char *months[] = { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December",
                             "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };

static char *dates[] = { "CET", "UTC", "GMT", "EET" };
