x-networks: &networks
  networks:
    - kospam

services:
  mysql:
    image: mariadb:11.6.2
    container_name: mysql
    restart: unless-stopped
    <<: *networks
    cap_drop:
      - ALL
    cap_add:
      - dac_override
      - setuid
      - setgid
    environment:
      - MYSQL_DATABASE=aaaaa
      - MYSQL_USER=kospam
      - MYSQL_PASSWORD=kospam123
      - MYSQL_ROOT_PASSWORD=abcde123
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --plugin-load=file_key_management
    volumes:
      - db_data:/var/lib/mysql

  postfix:
    image: sutoj/postfix:kospam
    container_name: mail.aaa.fu
    init: true
    <<: *networks
    volumes:
      - ./server.pem:/etc/postfix/server.pem

  kospam:
    image: sutoj/kospam:alpine
    container_name: kospam
    init: true
    networks:
      - kospam
    environment:
      - MYSQL_HOSTNAME=mysql
      - MYSQL_DATABASE=kospam
      - MYSQL_USER=kospam
      - MYSQL_PASSWORD=kospam123
      - MYSQL_ROOT_PASSWORD=abcde123
      - MYSQL_DUMP=/kospam.sql.gz
    volumes:
      - ./kospam.conf:/etc/kospam/kospam.conf
      - ./server.pem:/etc/kospam/kospam.pem
      - ./kospam.sql.gz:/kospam.sql.gz
    ports:
      - "10025:10025"
    depends_on:
      - "mysql"
      - "postfix"

volumes:
  db_data: {}

networks:
  kospam:
    name: kospam
