.\" Manual is created by Janos SUTO, 2006.01.31
.TH "CLAPF" "8" "Januar 31, 2006" "Janos SUTO" "Clapf network filter"
.SH "NAME"
.LP 
clapf \- a modular network filter for postfix
.SH "SYNOPSIS"
.LP 
clapf [options]
.SH "DESCRIPTION"
.LP 

clapf is a modular network filter for postfix. It includes a statistical
(inverse chi-square) antispam module, the blackhole feature and antivirus
support (libclamav, AVG Linux, avast! and Kasperky) preventing virus
infection as well as a cgi and a command line interface to easily train
the token database.

.SH "OPTIONS"
.LP

.TP
\fB\-h\fR
Print help information and exit.

.TP
\fB\-V\fR
Print the version number and exit.

.TP
\fB\-c FILE\fR
Read configuration from FILE.

.SH "CONFIG FILE OPTIONS"
.LP

You may find the detailed configuration options in the example.conf
or please check the online documentation at http://clapf.acts.hu/ or
http://clapf.sf.net/


.SH "MORE INFORMATION"
.LP
Look at the file called example.conf for the defaults and some explanation.

.SH "FILES"
.LP
/usr/local/etc/clapf.conf

.SH "LATEST VERSION"
.LP
Please check the primary site: http://clapf.acts.hu/ or the Sourceforge mirror
http://clapf.sf.net/ for the latest and hottest version of clapf as well as
online documentation.

.SH "AUTHOR"
.LP
Janos SUTO <sj@acts.hu>
