.\" Manual is created by Janos SUTO, 2006.01.18
.TH "PARSEMBOX" "1" "Januar 18, 2006" "Janos SUTO" "Clapf network filter"
.SH "NAME"
.LP 
parsembox \- parse an mbox format mailbox
.SH "SYNOPSIS"
.LP
parsembox <mbox format mailbox file>

.SH "DESCRIPTION"
.LP 

parsembox reads and parses an mbox format mailbox file then prints out its tokens.
You should not use it directly instead use one of the the util/db_init_*.sh shell
scripts to invoke it.

.SH "EXAMPLE"
.LP

.TP
Parse the HAM mailbox from the file 'ham.mbox'
.TP
\fBparsembox ham.mbox

.SH "FILES"
.LP
/usr/local/etc/clapf.conf

.SH "LATEST VERSION"
.LP
Please check http://clapf.acts.hu/ for the latest and hottest version of clapf as well as
online documentation.

.SH "AUTHOR"
.LP
Janos SUTO <sj@acts.hu>
