.\" Manual is created by Janos SUTO, 2006.04.11
.TH "PASSMAIL" "1" "April 11, 2006" "Janos SUTO" "Clapf network filter"
.SH "NAME"
.LP 
passmail \- delivers spam into the user's own spam quarantine

.SH "DESCRIPTION"
.LP 

passmail is invoked normally by maildrop to let the spam be delivered to
the user's spam quarantine directory.

.SH "EXAMPLE"
.LP

.TP
if(/^X-Clapf-spamicity: Yes/:h)
.LP
{
.LP
       to "|/usr/local/bin/passmail"
.TP
}

.SH "FILES"
.LP
/usr/local/etc/clapf.conf

.SH "LATEST VERSION"
.LP
Please check the primary site: http://clapf.acts.hu/ or the Sourceforge mirror
http://clapf.sf.net/ for the latest and hottest version of clapf as well as
online documentation.

.SH "AUTHOR"
.LP
Janos SUTO <sj@acts.hu>
