.\" Manual is created by Janos SUTO, 2006.06.29
.TH "SPAMDROP" "1" "Januar 18, 2006" "Janos SUTO" "Clapf network filter"
.SH "NAME"
.LP 
spamdrop \- check whether the given RFC-822 is spam or not
.SH "SYNOPSIS"
.LP 
cat <RFC-822 formatted message file> | spamdrop -c <configuration file> -p
.SH "DESCRIPTION"
.LP 

spamdrop is a command line utility to determine whether the incoming message
is spam or not. It reads its configuration and takes the message from the
standard input. Then it returns 1 if the message is spam or 0 otherwise.
If using the -p command line switch it will print the message to the
standard output. Spamdrop is designed to collaborate with maildrop.



.SH "OPTIONS"
.LP

.TP
\fB\-c\fR
Use the given configuration file instead the default (/usr/local/etc/clapf.conf).

.TP
\fB\-p\fR
Print the given message to the standard output and inserting some extra headers.


.SH "EXAMPLE"
.LP

To use spamdrop with maildrop you may use the following configuration snippet:

.nf
xfilter "/usr/local/bin/spamdrop -p"

if(/^X-Clapf-spamicity: Yes/:h)
{
        to "mail/junk"
}
to "Mailbox"

.SH "FILES"
.LP
/usr/local/etc/clapf.conf

.SH "LATEST VERSION"
.LP
Please check the primary site: http://clapf.acts.hu/ or the Sourceforge mirror
http://clapf.sf.net/ for the latest and hottest version of clapf as well as
online documentation.

.SH "AUTHOR"
.LP
Janos SUTO <sj@acts.hu>
