.\" Manual is created by Janos SUTO, 2006.01.18
.TH "SPAMTEST" "1" "Januar 18, 2006" "Janos SUTO" "Clapf network filter"
.SH "NAME"
.LP 
spamtest \- test the spam decision on a single RFC-822 message
.SH "SYNOPSIS"
.LP 
spamtest <configuration file> <RFC-822 formatted message file>
.SH "DESCRIPTION"
.LP 

spamtest is a command line utility for testing the spam decision mechanism of
clapf. It reads its configuration and takes a RFC-822 formatted message file
and prints out its spamicity as well as to spaminess of each tokens.

.SH "EXAMPLE"
.LP

.TP
To check the message in the file 'letter7'
.TP
\fBspamtest /usr/local/etc/clapf.conf letter7

.SH "FILES"
.LP
/usr/local/etc/clapf.conf

.SH "LATEST VERSION"
.LP
Please check the primary site: http://clapf.acts.hu/ or the Sourceforge mirror
http://clapf.sf.net/ for the latest and hottest version of clapf as well as
online documentation.

.SH "AUTHOR"
.LP
Janos SUTO <sj@acts.hu>
