<?

// titles

$TITLE['/index.php'] = 'clapf web UI - Kezdõlap';
$TITLE['/whitelist.php'] = 'Fehérlista';
$TITLE['/stat.php'] = 'Statisztika';
$TITLE['/q.php'] = 'Karantén';
$TITLE['/users.php'] = 'Felhasználó menedzselés';
$TITLE['/policy.php'] = 'Házirend';


$ADD_NEW_USER = "Új felhasználó hozzáadása";

$BACK = "Vissza";

$CANCEL = "Mégse";
$CGI_DAILY_REPORT = "Napi riport";
$CGI_MONTHLY_REPORT = "Havi riport";

$DATE = "Dátum";
$DELIVER = "Kézbesítés";

$EMAIL_ADDRESS = "Email cím";
$ERROR = "Hiba";
$EXISTING_USERS = "Létezõ felhasználó";

$FAILED_TO_REMOVE = "Hiba az eltávolításkor";
$FIRST = "Elsõ";
$FROM = "Feladó";

$HOME = "Kezdõlap";

$LAST = "Utolsó";

$NEXT = "Következõ";
$NO_SENDER = "nincs feladó";
$NO_SUBJECT = "nincs tárgy";
$NUMBER_OF_SPAM_MESSAGES_IN_QUARANTINE = "A spam üzenetek száma a karanténban";

$PREVIOUS = "Elõzõ";
$PURGE_SELECTED_MESSAGES = "Kiválasztott üzenetek eltávolítása";
$PURGED = "Eltávolítva";

$QUARANTINE = "Karantén";

$POLICY = "Házirend";

$REMOVE = "Törlés";

$SELECT_ALL = "Mindegyik kijelölése";
$STATS = "Statisztika";
$SUBJECT = "Tárgy";
$SUCCESSFULLY_REMOVED = "A törlés sikerült";

$TOTAL = "Összes";

$USERLIST = "Felhasználók listája";
$USERNAME = "Felhasználónév";
$USERID = "Felhasználó azonosíta";
$USER_MANAGEMENT = "Felhasználó menedzselés";

$WHITELIST = "Fehérlista";
$WHITELIST_SETTINGS = "Fehérlista beállítása";

$YOU_ARE = "Ön";


// error messages

$err_not_authenticated = "Ön nem azonosította magát";
$err_connect_db = "Adatbázis kapcsolat hiba";
$err_sql_error = "SQL hiba";
$err_NaN = "Nem szám";
$err_successfully_modified = "Sikeresen módosítva";
$err_invalid_message_id = "Helytelen üzenet azonosító";
$err_existing_user = "A felhasználó már létezik";
$err_added_user_successfully = "Felhasználó hozzáadása sikerült";
$err_failed_to_remove_user = "Nem sikerült a felhasználó törlése";
$err_removed_user_successfully = "Felhasználó törlése sikerült";
$err_you_are_not_admin = "Ön nem adminisztrátor szintû felhasználó";

$err_message_delivered = "Üzenet sikeresen továbbítva: ";
$err_message_failed_to_deliver = "Sikertelen üzenet továbbítás: ";

?>
