<?

// titles

$TITLE['/index.php'] = 'clapf web UI - Home';
$TITLE['/whitelist.php'] = 'Whitelist';
$TITLE['/stat.php'] = 'Statistics';
$TITLE['/q.php'] = 'Quarantine';
$TITLE['/users.php'] = 'User management';
$TITLE['/policy.php'] = 'Policy';


$ADD_NEW_USER = "Add new user";

$BACK = "Back";

$CANCEL = "Cancel";
$CGI_DAILY_REPORT = "Daily report";
$CGI_MONTHLY_REPORT = "Monthly report";

$DATE = "Date";
$DELIVER = "Deliver";

$EMAIL_ADDRESS = "Email address";
$ERROR = "Error";
$EXISTING_USERS = "Existing users";

$FAILED_TO_REMOVE = "Failed to remove";
$FIRST = "First";
$FROM = "From";

$HOME = "Home";

$LAST = "Last";

$NEXT = "Next";
$NO_SENDER = "no sender";
$NO_SUBJECT = "no subject";
$NUMBER_OF_SPAM_MESSAGES_IN_QUARANTINE = "Number of spam messages in the quarantine";

$PREVIOUS = "Previous";
$PURGE_SELECTED_MESSAGES = "Purge selected messages";
$PURGED = "Purged";

$QUARANTINE = "Quarantine";

$POLICY = "Policy";

$REMOVE = "Remove";

$SELECT_ALL = "Select all";
$STATS = "Statistics";
$SUBJECT = "Subject";
$SUCCESSFULLY_REMOVED = "Successfully removed";

$TOTAL = "Total";

$USERLIST = "User's list";
$USERNAME = "Username";
$USERID = "User id";
$USER_MANAGEMENT = "User management";

$WHITELIST = "Whitelist";
$WHITELIST_SETTINGS = "Whitelist settings";

$YOU_ARE = "You are";


// error messages

$err_not_authenticated = "You are not authenticated";
$err_connect_db = "Database connection error";
$err_sql_error = "SQL error";
$err_NaN = "Not a number";
$err_successfully_modified = "Successfully modified";
$err_invalid_message_id = "Invalid message id";
$err_existing_user = "User already exists";
$err_added_user_successfully = "User added successfully";
$err_failed_to_remove_user = "User failed to remove";
$err_removed_user_successfully = "User removed successfully";
$err_you_are_not_admin = "You are not an admin user";

$err_message_delivered = "Message delivered to";
$err_message_failed_to_deliver = "Message failed to deliver to";

?>
