#!/bin/sh

### BEGIN INIT INFO
# Provides:          clapf-maillog
# Required-Start:    $syslog
# Should-Start:      mysql
# Required-Stop:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 6
# Short-Description: Clapf mail log data collector daemon
# Description:       Clapf mail log data collector daemon
### END INIT INFO

PREFIX="/data/apps/clapf/current"
DESC="Clapf mail log data collector daemon"
PID=`${PREFIX}/sbin/clapfconf |grep historypid |cut -f2 -d=`
CONFIG="${PREFIX}/etc/clapf.conf"
COMMAND="/usr/bin/perl ${PREFIX}/libexec/clapf/maillog.pl ${CONFIG}"

. /lib/lsb/init-functions

check_status(){
	cat /proc/$PID/cmdline | xargs -0 echo | grep -q ^"${COMMAND}"$
}

check_status_verbose(){
    cat /proc/$PID/cmdline | xargs -0 echo | grep ^"${COMMAND}"$
}

case "$1" in
	start)
		log_daemon_msg "Starting $DESC" maillog.pl
		if check_status;
		 then
			log_failure_msg "$DESC is already running."
			exit 1;
		 else 
			if start-stop-daemon --start --quiet --pidfile $PID --exec ${PREFIX}/libexec/clapf/maillog.pl -- ${CONFIG}; then
				log_end_msg 0
			 else
				log_end_msg 1
		 	fi
		fi
	;;

	stop)
        log_daemon_msg "Stopping $DESC" maillog.pl
        if start-stop-daemon --stop --quiet --pidfile $PID; then
            log_end_msg 0
        else
            log_end_msg 1
        fi
   ;;

	restart)
		$0 stop
		sleep 1
		$0 start
   ;;

	status)
		check_status || ${COMMAND} is not started.

*)
   echo "usage $0 start|stop|restart|status"
esac

