name: Build and test

on:
  pull_request:
    types:
      - opened # PR created
      - synchronize # commit pushed to PR
      - reopened # closed PR reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

env:
  IMAGE_NAME: sutoj/kospam
  TEST_TAG: test
  DISTRO: noble
  PROJECT_ID: kospam
  ARCH: amd64

jobs:
  build:
    runs-on:
      - ubuntu-latest

    outputs:
      IMAGE_TAG: ${{ steps.get-version.outputs.IMAGE_TAG }}
      COMMIT_ID: ${{ steps.get-version.outputs.COMMIT_ID }}
      VERSION: ${{ steps.get-version.outputs.VERSION }}
      PACKAGE: ${{ steps.build-package.outputs.PACKAGE }}
      BUILD_IMAGE: ${{ steps.filter.outputs.build_image }}

    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get-version
        uses: ./.github/actions/version

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            build_image:
              - 'util/**'
              - 'webui/**'

      - name: Build and publish Go apps
        id: build-go
        uses: ./.github/actions/build/go
        with:
          ARCH: ${{ env.ARCH }}
          COMMIT_ID: ${{ steps.get-version.outputs.COMMIT_ID }}
          VERSION: ${{ steps.get-version.outputs.VERSION }}

      - name: Build alpine image
        id: alpine-image
        uses: ./.github/actions/build/alpine
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}:${{ env.TEST_TAG }}
          LOAD: false
          PLATFORMS: linux/${{ env.ARCH }}
          PUSH: true

      - if: steps.filter.outputs.build_image == 'true'
        name: Build package
        id: build-package
        uses: ./.github/actions/build/package
        with:
          ARCH: ${{ env.ARCH }}
          BUILDER_IMAGE: sutoj/builder:${{ env.DISTRO }}
          COMMIT_ID: ${{ steps.get-version.outputs.COMMIT_ID }}
          DISTRO: ${{ env.DISTRO }}
          PROJECT_ID: ${{ env.PROJECT_ID }}
          VERSION: ${{ steps.get-version.outputs.VERSION }}

      - if: steps.filter.outputs.build_image == 'true'
        name: Build image
        id: ubuntu-image
        uses: ./.github/actions/build/image
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}:${{ env.TEST_TAG }}-ubuntu
          LOAD: false
          PACKAGE: ${{ env.PROJECT_ID }}_${{ steps.get-version.outputs.VERSION }}-${{ env.DISTRO }}-${{ steps.get-version.outputs.COMMIT_ID }}
          PLATFORMS: linux/${{ env.ARCH }}
          PUSH: true

  run-tests:
    runs-on:
      - ubuntu-latest

    needs:
      - build

    strategy:
      matrix:
        testcase: ['case1']

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            tests
            .github
          sparse-checkout-cone-mode: false

      - name: Download package
        uses: actions/download-artifact@v4
        with:
          path: tests
          merge-multiple: true

      - name: Run tests
        uses: ./.github/actions/test
        with:
          MINIO_URL: ${{ secrets.MINIO_URL }}
          MINIO_USER: ${{ secrets.MINIO_USER }}
          MINIO_PASSWORD: ${{ secrets.MINIO_PASSWORD }}
          TESTCASE: ${{ matrix.testcase }}
          TEST_TAG: ${{ env.TEST_TAG }}
